---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: tailscale-auth
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: TAILSCALE_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: TAILSCALE_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: TAILSCALE_CLIENT_SECRET
---
