---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeGPT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeGPT
  template:
    metadata:
      labels:
        app: homeGPT
    spec:
      containers:
      - name: homeGPT
        image: ghcr.io/bensonphillipsiv/homegpt:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        envFrom:
          - configMapRef:
              name: homeGPT
          - secretRef:
              name: homeGPT
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["b1"]
---
