apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metrics-server

helmCharts:
- name: metrics-server
  repo: https://kubernetes-sigs.github.io/metrics-server/
  version: 3.13.0
  releaseName: metrics-server
  valuesInline:
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
    metrics:
      enabled: true
