---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: the_block
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: the_block
  data:
    - secretKey: HOMEASSISTANT_TOKEN
      remoteRef:
        key: HOMEASSISTANT_TOKEN
---
