apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - ingress.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 9.4.5
    releaseName: grafana
    valuesInline:
      grafana.ini:
        auth:
          disable_login_form: true
        auth.anonymous:
          enabled: true
          org_role: Admin
      admin:
        existingSecret: null
        userKey: null
        passwordKey: null
      adminUser: null
      adminPassword: null
