---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
        - name: mediamtx
          image: bluenviron/mediamtx:1.13.1
          env:
            - name: MTX_RTSPTRANSPORTS
              value: "tcp"
          ports:
            - name: rtsp
              containerPort: 8554
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mediamtx
  labels:
    app: mediamtx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.123
  selector:
    app: mediamtx
  ports:
    - name: rtsp
      protocol: TCP
      port: 8554
      targetPort: 8554
---
