---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-block
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-block
  template:
    metadata:
      labels:
        app: the-block
    spec:
      containers:
      - name: the-block
        image: ghcr.io/bensonphillipsiv/the_block:newest-build
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: the-block
          - secretRef:
              name: the-block
---
